### PR TITLE
euroedit: added European Commission subnets

### PR DESCRIPTION
**Pull request by stefan2904**
source: https://dnslytics.com/bgp/as42848

### CODE REVIEW

**Comment by stefangrotz** [comment]
Maybe we need an extra account called unionedit?

**Comment by stefan2904** [comment]
you do: https://twitter.com/euroedit

**Comment by fleaz** [comment]
Thank you :)

**Comment by stefan2904** [comment]
@fleaz is this deployed already? than I can do a test edit. ;-)

**Comment by fleaz** [comment]
> @fleaz is this deployed already? than I can do a test edit. ;-)

Yes it is. Try it :)

**Comment by stefan2904** [comment]
works. nice!

**Comment by stefan2904** [comment]
something might be wrong, see this edit: https://twitter.com/euroedit/status/1225434131720556545
the edit is correct (made from EC network), but the title in the tweet is from the wrong article?

**Comment by fleaz** [comment]
Uhh, thanks for the heads up! Just found a few more examples where the title was wrong. Will look into this.

**Pull request merged**
